sonar.exclusions=docs/**,**/coverage/**,report/**
sonar.tests=modules
sonar.test.inclusions=modules/**/*.test.ts,modules/**/test/**/*.ts
sonar.cpd.exclusions=modules/database/drizzle/meta/**,modules/database/drizzle/*.sql
