sonar.sources=modules
sonar.exclusions=docs/**,**/coverage/**,report/**
sonar.tests=modules
sonar.test.inclusions=modules/**/*.test.ts,modules/**/test/**/*.ts
sonar.cpd.exclusions=modules/database/drizzle/meta/**,modules/database/drizzle/*.sql
sonar.javascript.lcov.reportPaths=modules/backend/coverage/lcov.info,modules/frontend/coverage/lcov.info,modules/database/coverage/lcov.info
sonar.organization=nhsbsa-rixue
sonar.projectKey=cloudflare-demo
