sonar.organization=nhsbsa-rixue
sonar.projectKey=cloudflare-demo

sonar.sources=modules
sonar.tests=modules
sonar.test.inclusions=modules/**/*.test.ts,modules/**/test/**/*.ts
sonar.exclusions=docs/**,**/coverage/**,report/**,modules/utils/**
sonar.cpd.exclusions=modules/database/drizzle/meta/**,modules/database/drizzle/*.sql

sonar.typescript.tsconfigPaths=modules/backend/tsconfig.json,modules/database/tsconfig.json,modules/frontend/tsconfig.json
sonar.javascript.lcov.reportPaths=modules/backend/coverage/lcov.info,modules/frontend/coverage/lcov.info,modules/database/coverage/lcov.info
sonar.testExecutionReportPaths=modules/backend/test-report.xml,modules/frontend/test-report.xml,modules/database/test-report.xml
