name = "analyse-workflow"
main = "index.py"
compatibility_date = "2026-01-01"
compatibility_flags = ["python_workers"]

logpush = true

[observability]
enabled = true

[[workflows]]
name = "analyse-workflow"
binding = "ANALYSE_WORKFLOW"
class_name = "AnalyseWorkflow"
